--- # Poggit-CI Manifest. Open the CI at https://poggit.pmmp.io/ci/PresentKim/multilingual-resource-trait
branches:
  - main
projects:
  multilingual-resource-trait:
    model: virion
    type: library
    lint:
      phpstan: false
...